services:
  - type: web
    name: medical-diagnosis-ai
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: medical_diagnosis
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@medical-ai.com
      - key: ADMIN_PASSWORD
        sync: false 